export const COUNTRIES: any[] = [
{ codeIso: 'AD' , name: 'Andorre' },
{ codeIso: 'AE' , name: 'Émirats arabes unis' },
{ codeIso: 'AF' , name: 'Afghanistan' },
{ codeIso: 'AG' , name: 'Antigua-et-Barbuda' },
{ codeIso: 'AI' , name: 'Anguilla' },
{ codeIso: 'AL' , name: 'Albanie' },
{ codeIso: 'AM' , name: 'Arménie' },
{ codeIso: 'AO' , name: 'Angola' },
{ codeIso: 'AQ' , name: 'Antarctique' },
{ codeIso: 'AR' , name: 'Argentine' },
{ codeIso: 'AS' , name: 'Samoa américaines' },
{ codeIso: 'AT' , name: 'Autriche' },
{ codeIso: 'AU' , name: 'Australie' },
{ codeIso: 'AW' , name: 'Aruba' },
{ codeIso: 'AX' , name: 'Åland(les Îles)' },
{ codeIso: 'AZ' , name: 'Azerbaïdjan' },
{ codeIso: 'BA' , name: 'Bosnie-Herzégovine' },
{ codeIso: 'BB' , name: 'Barbade' },
{ codeIso: 'BD' , name: 'Bangladesh' },
{ codeIso: 'BE' , name: 'Belgique' },
{ codeIso: 'BF' , name: 'Burkina Faso' },
{ codeIso: 'BG' , name: 'Bulgarie' },
{ codeIso: 'BH' , name: 'Bahreïn' },
{ codeIso: 'BI' , name: 'Burundi' },
{ codeIso: 'BJ' , name: 'Bénin' },
{ codeIso: 'BL' , name: 'Saint-Barthélemy' },
{ codeIso: 'BM' , name: 'Bermudes' },
{ codeIso: 'BN' , name: 'Brunéi Darussalam' },
{ codeIso: 'BO' , name: 'Bolivie' },
{ codeIso: 'BQ' , name: 'Bonaire, Saint-Eustache et Saba' },
{ codeIso: 'BR' , name: 'Brésil' },
{ codeIso: 'BS' , name: 'Bahamas' },
{ codeIso: 'BT' , name: 'Bhoutan' },
{ codeIso: 'BV' , name: 'Bouvet (l\'Île)' },
{ codeIso: 'BW' , name: 'Botswana' },
{ codeIso: 'BY' , name: 'Bélarus' },
{ codeIso: 'BZ' , name: 'Belize' },
{ codeIso: 'CA' , name: 'Canada' },
{ codeIso: 'CC' , name: 'Cocos (les Îles)/ Keeling (les Îles)' },
{ codeIso: 'CD' , name: 'Congo (la République démocratique du)' },
{ codeIso: 'CF' , name: 'République centrafricaine' },
{ codeIso: 'CG' , name: 'Congo' },
{ codeIso: 'CH' , name: 'Suisse' },
{ codeIso: 'CI' , name: 'Côte d\'Ivoire' },
{ codeIso: 'CK' , name: 'Cook (les Îles)' },
{ codeIso: 'CL' , name: 'Chili' },
{ codeIso: 'CM' , name: 'Cameroun' },
{ codeIso: 'CN' , name: 'Chine' },
{ codeIso: 'CO' , name: 'Colombie' },
{ codeIso: 'CR' , name: 'Costa Rica' },
{ codeIso: 'CU' , name: 'Cuba' },
{ codeIso: 'CV' , name: 'Cabo Verde' },
{ codeIso: 'CW' , name: 'Curaçao' },
{ codeIso: 'CX' , name: 'Christmas (l\'Île)' },
{ codeIso: 'CY' , name: 'Chypre' },
{ codeIso: 'CZ' , name: 'Tchéquie' },
{ codeIso: 'DE' , name: 'Allemagne' },
{ codeIso: 'DJ' , name: 'Djibouti' },
{ codeIso: 'DK' , name: 'Danemark' },
{ codeIso: 'DM' , name: 'Dominique' },
{ codeIso: 'DO' , name: 'dominicaine (la République)' },
{ codeIso: 'DZ' , name: 'Algérie' },
{ codeIso: 'EC' , name: 'Équateur' },
{ codeIso: 'EE' , name: 'Estonie' },
{ codeIso: 'EG' , name: 'Égypte' },
{ codeIso: 'EH' , name: 'Sahara occidental' },
{ codeIso: 'ER' , name: 'Érythrée' },
{ codeIso: 'ES' , name: 'Espagne' },
{ codeIso: 'ET' , name: 'Éthiopie' },
{ codeIso: 'FI' , name: 'Finlande' },
{ codeIso: 'FJ' , name: 'Fidji' },
{ codeIso: 'FK' , name: 'Falkland (les Îles)/Malouines (les Îles)' },
{ codeIso: 'FM' , name: 'Micronésie (États fédérés de)' },
{ codeIso: 'FO' , name: 'Féroé (les Îles)' },
{ codeIso: 'FR' , name: 'France' },
{ codeIso: 'GA' , name: 'Gabon' },
{ codeIso: 'GB' , name: 'Royaume-Uni de Grande-Bretagne et d\'Irlande du Nord' },
{ codeIso: 'GD' , name: 'Grenade' },
{ codeIso: 'GE' , name: 'Géorgie' },
{ codeIso: 'GF' , name: 'Guyane française' },
{ codeIso: 'GG' , name: 'Guernesey' },
{ codeIso: 'GH' , name: 'Ghana' },
{ codeIso: 'GI' , name: 'Gibraltar' },
{ codeIso: 'GL' , name: 'Groenland' },
{ codeIso: 'GM' , name: 'Gambie' },
{ codeIso: 'GN' , name: 'Guinée' },
{ codeIso: 'GP' , name: 'Guadeloupe' },
{ codeIso: 'GQ' , name: 'Guinée équatoriale' },
{ codeIso: 'GR' , name: 'Grèce' },
{ codeIso: 'GS' , name: 'Géorgie du Sud-et-les Îles Sandwich du Sud' },
{ codeIso: 'GT' , name: 'Guatemala' },
{ codeIso: 'GU' , name: 'Guam' },
{ codeIso: 'GW' , name: 'Guinée-Bissau' },
{ codeIso: 'GY' , name: 'Guyana' },
{ codeIso: 'HK' , name: 'Hong Kong' },
{ codeIso: 'HM' , name: 'Heard-et-Îles MacDonald (l\'Île)' },
{ codeIso: 'HN' , name: 'Honduras' },
{ codeIso: 'HR' , name: 'Croatie' },
{ codeIso: 'HT' , name: 'Haïti' },
{ codeIso: 'HU' , name: 'Hongrie' },
{ codeIso: 'ID' , name: 'Indonésie' },
{ codeIso: 'IE' , name: 'Irlande' },
{ codeIso: 'IL' , name: 'Israël' },
{ codeIso: 'IM' , name: 'Île de Man' },
{ codeIso: 'IN' , name: 'Inde' },
{ codeIso: 'IO' , name: 'Indien (le Territoire britannique de l\'océan)' },
{ codeIso: 'IQ' , name: 'Iraq' },
{ codeIso: 'IR' , name: 'Iran (République Islamique d\')' },
{ codeIso: 'IS' , name: 'Islande' },
{ codeIso: 'IT' , name: 'Italie' },
{ codeIso: 'JE' , name: 'Jersey' },
{ codeIso: 'JM' , name: 'Jamaïque' },
{ codeIso: 'JO' , name: 'Jordanie' },
{ codeIso: 'JP' , name: 'Japon' },
{ codeIso: 'KE' , name: 'Kenya' },
{ codeIso: 'KG' , name: 'Kirghizistan' },
{ codeIso: 'KH' , name: 'Cambodge' },
{ codeIso: 'KI' , name: 'Kiribati' },
{ codeIso: 'KM' , name: 'Comores' },
{ codeIso: 'KN' , name: 'Saint-Kitts-et-Nevis' },
{ codeIso: 'KP' , name: 'Corée (la République populaire démocratique de)' },
{ codeIso: 'KR' , name: 'Corée (la République de)' },
{ codeIso: 'KW' , name: 'Koweït' },
{ codeIso: 'KY' , name: 'Caïmans (les Îles)' },
{ codeIso: 'KZ' , name: 'Kazakhstan' },
{ codeIso: 'LA' , name: 'Lao, République démocratique populaire' },
{ codeIso: 'LB' , name: 'Liban' },
{ codeIso: 'LC' , name: 'Sainte-Lucie' },
{ codeIso: 'LI' , name: 'Liechtenstein' },
{ codeIso: 'LK' , name: 'Sri Lanka' },
{ codeIso: 'LR' , name: 'Libéria' },
{ codeIso: 'LS' , name: 'Lesotho' },
{ codeIso: 'LT' , name: 'Lituanie' },
{ codeIso: 'LU' , name: 'Luxembourg' },
{ codeIso: 'LV' , name: 'Lettonie' },
{ codeIso: 'LY' , name: 'Libye' },
{ codeIso: 'MA' , name: 'Maroc' },
{ codeIso: 'MC' , name: 'Monaco' },
{ codeIso: 'MD' , name: 'Moldova, République de' },
{ codeIso: 'ME' , name: 'Monténégro' },
{ codeIso: 'MF' , name: 'Saint-Martin (partie française)' },
{ codeIso: 'MG' , name: 'Madagascar' },
{ codeIso: 'MH' , name: 'Marshall (Îles)' },
{ codeIso: 'MK' , name: 'Macédoine (l\'ex‑République yougoslave de)' },
{ codeIso: 'ML' , name: 'Mali' },
{ codeIso: 'MM' , name: 'Myanmar' },
{ codeIso: 'MN' , name: 'Mongolie' },
{ codeIso: 'MO' , name: 'Macao' },
{ codeIso: 'MP' , name: 'Mariannes du Nord (les Îles)' },
{ codeIso: 'MQ' , name: 'Martinique' },
{ codeIso: 'MR' , name: 'Mauritanie' },
{ codeIso: 'MS' , name: 'Montserrat' },
{ codeIso: 'MT' , name: 'Malte' },
{ codeIso: 'MU' , name: 'Maurice' },
{ codeIso: 'MV' , name: 'Maldives' },
{ codeIso: 'MW' , name: 'Malawi' },
{ codeIso: 'MX' , name: 'Mexique' },
{ codeIso: 'MY' , name: 'Malaisie' },
{ codeIso: 'MZ' , name: 'Mozambique' },
{ codeIso: 'NA' , name: 'Namibie' },
{ codeIso: 'NC' , name: 'Nouvelle-Calédonie' },
{ codeIso: 'NE' , name: 'Niger' },
{ codeIso: 'NF' , name: 'Norfolk (l\'Île)' },
{ codeIso: 'NG' , name: 'Nigéria' },
{ codeIso: 'NI' , name: 'Nicaragua' },
{ codeIso: 'NL' , name: 'Pays-Bas' },
{ codeIso: 'NO' , name: 'Norvège' },
{ codeIso: 'NP' , name: 'Népal' },
{ codeIso: 'NR' , name: 'Nauru' },
{ codeIso: 'NU' , name: 'Niue' },
{ codeIso: 'NZ' , name: 'Nouvelle-Zélande' },
{ codeIso: 'OM' , name: 'Oman' },
{ codeIso: 'PA' , name: 'Panama' },
{ codeIso: 'PE' , name: 'Pérou' },
{ codeIso: 'PF' , name: 'Polynésie française' },
{ codeIso: 'PG' , name: 'Papouasie-Nouvelle-Guinée' },
{ codeIso: 'PH' , name: 'Philippines' },
{ codeIso: 'PK' , name: 'Pakistan' },
{ codeIso: 'PL' , name: 'Pologne' },
{ codeIso: 'PM' , name: 'Saint-Pierre-et-Miquelon' },
{ codeIso: 'PN' , name: 'Pitcairn' },
{ codeIso: 'PR' , name: 'Porto Rico' },
{ codeIso: 'PS' , name: 'Palestine, État de' },
{ codeIso: 'PT' , name: 'Portugal' },
{ codeIso: 'PW' , name: 'Palaos' },
{ codeIso: 'PY' , name: 'Paraguay' },
{ codeIso: 'QA' , name: 'Qatar' },
{ codeIso: 'RE' , name: 'Réunion' },
{ codeIso: 'RO' , name: 'Roumanie' },
{ codeIso: 'RS' , name: 'Serbie' },
{ codeIso: 'RU' , name: 'Russie (la Fédération de)' },
{ codeIso: 'RW' , name: 'Rwanda' },
{ codeIso: 'SA' , name: 'Arabie saoudite' },
{ codeIso: 'SB' , name: 'Salomon (Îles)' },
{ codeIso: 'SC' , name: 'Seychelles' },
{ codeIso: 'SD' , name: 'Soudan' },
{ codeIso: 'SE' , name: 'Suède' },
{ codeIso: 'SG' , name: 'Singapour' },
{ codeIso: 'SH' , name: 'Sainte-Hélène, Ascension et Tristan da Cunha' },
{ codeIso: 'SI' , name: 'Slovénie' },
{ codeIso: 'SJ' , name: 'Svalbard et l\'Île Jan Mayen' },
{ codeIso: 'SK' , name: 'Slovaquie' },
{ codeIso: 'SL' , name: 'Sierra Leone' },
{ codeIso: 'SM' , name: 'Saint-Marin' },
{ codeIso: 'SN' , name: 'Sénégal' },
{ codeIso: 'SO' , name: 'Somalie' },
{ codeIso: 'SR' , name: 'Suriname' },
{ codeIso: 'SS' , name: 'Soudan du Sud' },
{ codeIso: 'ST' , name: 'Sao Tomé-et-Principe' },
{ codeIso: 'SV' , name: 'El Salvador' },
{ codeIso: 'SX' , name: 'Saint-Martin (partie néerlandaise)' },
{ codeIso: 'SY' , name: 'République arabe syrienne' },
{ codeIso: 'SZ' , name: 'Swaziland' },
{ codeIso: 'TC' , name: 'Turks-et-Caïcos (les Îles)' },
{ codeIso: 'TD' , name: 'Tchad' },
{ codeIso: 'TF' , name: 'Terres australes françaises' },
{ codeIso: 'TG' , name: 'Togo' },
{ codeIso: 'TH' , name: 'Thaïlande' },
{ codeIso: 'TJ' , name: 'Tadjikistan' },
{ codeIso: 'TK' , name: 'Tokelau' },
{ codeIso: 'TL' , name: 'Timor-Leste' },
{ codeIso: 'TM' , name: 'Turkménistan' },
{ codeIso: 'TN' , name: 'Tunisie' },
{ codeIso: 'TO' , name: 'Tonga' },
{ codeIso: 'TR' , name: 'Turquie' },
{ codeIso: 'TT' , name: 'Trinité-et-Tobago' },
{ codeIso: 'TV' , name: 'Tuvalu' },
{ codeIso: 'TW' , name: 'Taïwan (Province de Chine)' },
{ codeIso: 'TZ' , name: 'Tanzanie, République-Unie de' },
{ codeIso: 'UA' , name: 'Ukraine' },
{ codeIso: 'UG' , name: 'Ouganda' },
{ codeIso: 'UM' , name: 'Îles mineures éloignées des États-Unis' },
{ codeIso: 'US' , name: 'États-Unis d\'Amérique' },
{ codeIso: 'UY' , name: 'Uruguay' },
{ codeIso: 'UZ' , name: 'Ouzbékistan' },
{ codeIso: 'VA' , name: 'Saint-Siège' },
{ codeIso: 'VC' , name: 'Saint-Vincent-et-les Grenadines' },
{ codeIso: 'VE' , name: 'Venezuela (République bolivarienne du)' },
{ codeIso: 'VG' , name: 'Vierges britanniques (les Îles)' },
{ codeIso: 'VI' , name: 'Vierges des États-Unis (les Îles)' },
{ codeIso: 'VN' , name: 'Viet Nam' },
{ codeIso: 'VU' , name: 'Vanuatu' },
{ codeIso: 'WF' , name: 'Wallis-et-Futuna' },
{ codeIso: 'WS' , name: 'Samoa' },
{ codeIso: 'YE' , name: 'Yémen' },
{ codeIso: 'YT' , name: 'Mayotte' },
{ codeIso: 'ZA' , name: 'Afrique du Sud' },
{ codeIso: 'ZM' , name: 'Zambie' },
{ codeIso: 'ZW' , name: 'Zimbabwe' }
];
